#!/bin/sh

# Path to the swift file
filePath="$(dirname "$0")/BuildHelpers.swift"

# Content to be written
content="// DO NOT EDIT THIS FILE. IT IS AUTOMATICALLY GENERATED.

struct BuildHelpers {
  struct Constants {
    static let isCIEnvironment: Bool = true
  }
}"

# Write the content to the swift file
echo "${content}" > "${filePath}"