#!/usr/bin/env python3
"""Plan and run shards of the UI test suite, locally or on a remote Mac.

The suite is one test class per numbered test, run under four schemes, which
is a few hundred cases and several hours end to end in one line. Splitting it
into shards lets a CI job fan out across machines and rejoin on the exit code.

  scripts/run-tests.py plan --shards 10
  scripts/run-tests.py run --scheme "UI Tests -swift -automatic" --shard 0/3

`plan` prints the job matrix as JSON; `run` executes one entry of it. Pass
`--runner lim` to build and run on a remote Mac instead of this one.
"""

import argparse
import json
import os
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
GENERATED_TESTS = ROOT / "UI Tests" / "Autogenerated" / "Tests.swift"
PROJECT = "UI Tests.xcodeproj"
TEST_TARGET = "Automated UI Testing"

SCHEMES = [
  "UI Tests -swift -automatic",
  "UI Tests -swift -advanced",
  "UI Tests -objc -automatic",
  "UI Tests -objc -advanced",
]

# The simulator the snapshots were recorded against. Only used locally; a
# remote run takes whichever simulator the fleet attaches.
DEFAULT_DESTINATION = "platform=iOS Simulator,name=iPhone 17 Pro,OS=latest"

CLASS_PATTERN = re.compile(r"^class (Automated_UI_Testing_test\d+):", re.MULTILINE)


def test_classes() -> list[str]:
  """Every generated test class, in the order the generator emitted them."""
  if not GENERATED_TESTS.exists():
    sys.exit(f"No generated tests at {GENERATED_TESTS}")

  names = CLASS_PATTERN.findall(GENERATED_TESTS.read_text(encoding="utf-8"))
  if not names:
    sys.exit(f"Found no test classes in {GENERATED_TESTS}")
  return names


def shard_of(names: list[str], index: int, count: int) -> list[str]:
  """Deal the classes out round-robin so every shard gets a similar mix.

  Test numbers are roughly grouped by feature, so slicing into contiguous
  blocks would hand one shard all the slow paywall tests.
  """
  if not 0 <= index < count:
    sys.exit(f"Shard {index} is out of range for {count} shards")
  return names[index::count]


def plan(shards_per_scheme: int, schemes: list[str]) -> list[dict]:
  names = test_classes()
  return [
    {
      "scheme": scheme,
      "shard": f"{index}/{shards_per_scheme}",
      "cases": len(shard_of(names, index, shards_per_scheme)),
    }
    for scheme in schemes
    for index in range(shards_per_scheme)
  ]


def only_testing_args(names: list[str]) -> list[str]:
  return [f"{TEST_TARGET}/{name}" for name in names]


def run(scheme: str, index: int, count: int, runner: str, destination: str, dry_run: bool, record: bool) -> int:
  selected = shard_of(test_classes(), index, count)

  # xcodebuild hands TEST_RUNNER_-prefixed variables to the test process with
  # the prefix taken off, which is the only way into a UI test runner.
  environment = dict(os.environ)
  if record:
    environment["TEST_RUNNER_SNAPSHOT_RECORD"] = "1"

  if runner == "local":
    command = [
      "xcodebuild", "test",
      "-project", PROJECT,
      "-scheme", scheme,
      "-destination", destination,
    ]
    for identifier in only_testing_args(selected):
      command += ["-only-testing", identifier]
  else:
    command = ["lim", "xcode", "test", ".", "--scheme", scheme]
    for identifier in only_testing_args(selected):
      command += ["--only-testing", identifier]
    # Give the run its own sandbox and simulator so concurrent shards don't
    # land on each other, and so they clean themselves up when the job ends.
    command += ["--inactivity-timeout", "30m"]

  print(f"Shard {index}/{count} of {scheme}: {len(selected)} cases", file=sys.stderr)
  if dry_run:
    print(" ".join(repr(part) if " " in part else part for part in command))
    return 0

  return subprocess.call(command, cwd=ROOT, env=environment)


def main() -> None:
  parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
  subcommands = parser.add_subparsers(dest="command", required=True)

  planner = subcommands.add_parser("plan", help="Print the job matrix as JSON")
  planner.add_argument("--shards", type=int, default=1, help="Shards per scheme")
  planner.add_argument("--scheme", action="append", dest="schemes", help="Limit to this scheme; repeatable")

  runner = subcommands.add_parser("run", help="Run one shard")
  runner.add_argument("--scheme", required=True)
  runner.add_argument("--shard", default="0/1", help="INDEX/COUNT, e.g. 2/10")
  runner.add_argument("--runner", choices=["local", "lim"], default="local")
  runner.add_argument("--destination", default=DEFAULT_DESTINATION, help="Local runs only")
  runner.add_argument("--dry-run", action="store_true", help="Print the command instead of running it")
  runner.add_argument("--record", action="store_true", help="Overwrite the stored snapshots instead of comparing")

  args = parser.parse_args()

  if args.command == "plan":
    schemes = args.schemes or SCHEMES
    unknown = [scheme for scheme in schemes if scheme not in SCHEMES]
    if unknown:
      sys.exit(f"Unknown scheme(s): {', '.join(unknown)}")
    print(json.dumps(plan(args.shards, schemes), indent=2))
    return

  if args.record and args.runner == "lim":
    sys.exit("--record needs a local run: a remote sandbox keeps the images it writes")

  if args.scheme not in SCHEMES:
    sys.exit(f"Unknown scheme: {args.scheme}")

  try:
    index, count = (int(part) for part in args.shard.split("/", 1))
  except ValueError:
    sys.exit(f"Expected shard as INDEX/COUNT, got {args.shard}")

  sys.exit(run(args.scheme, index, count, args.runner, args.destination, args.dry_run, args.record))


if __name__ == "__main__":
  main()
