// DO NOT EDIT THIS FILE. IT IS AUTOMATICALLY GENERATED.

import Foundation

@objc protocol Testable: AnyObject {
  var configuration: TestConfiguration { get }

  func test0() async throws
  func test1() async throws
  func test2() async throws
  func test3() async throws
  func test4() async throws
  func test5() async throws
  func test6() async throws
  func test7() async throws
  func test8() async throws
  func test9() async throws
  func test10() async throws
  func test11() async throws
  func test12() async throws
  func test13() async throws
  func test14() async throws
  func test15() async throws
  func test16() async throws
  func test17() async throws
  func test18() async throws
  func test19() async throws
  func test20() async throws
  func test21() async throws
  func test22() async throws
  func test23() async throws
  func test24() async throws
  func test25() async throws
  func test26() async throws
  func test27() async throws
  func test28() async throws
  func test29() async throws
  func test30() async throws
  func test31() async throws
  func test32() async throws
  func test33() async throws
  func test34() async throws
  func test35() async throws
  func test36() async throws
  func test37() async throws
  func test38() async throws
  func test39() async throws
  func test40() async throws
  func test41() async throws
  func test42() async throws
  func test43() async throws
  func test44() async throws
  func test45() async throws
  func test46() async throws
  func test47() async throws
  func test48() async throws
  func test49() async throws
  func test50() async throws
  func test51() async throws
  func test52() async throws
  func test53() async throws
  func test54() async throws
  func test55() async throws
  func test56() async throws
  func test57() async throws
  func test58() async throws
  func test59() async throws
  func test60() async throws
  func test61() async throws
  func test62() async throws
  func test63() async throws
  func test64() async throws
  func test65() async throws
  func test66() async throws
  func test67() async throws
  func test68() async throws
  func test69() async throws
  func test70() async throws
  func test71() async throws
  func test72() async throws
  func test73() async throws
  func test74() async throws
  func test75() async throws
  func test76() async throws
  func test77() async throws
  func test78() async throws
  func test79() async throws
  func test80() async throws
  func test81() async throws
  func test82() async throws

  @objc optional func testOptions0() -> TestOptions
  @objc optional func testOptions1() -> TestOptions
  @objc optional func testOptions2() -> TestOptions
  @objc optional func testOptions3() -> TestOptions
  @objc optional func testOptions4() -> TestOptions
  @objc optional func testOptions5() -> TestOptions
  @objc optional func testOptions6() -> TestOptions
  @objc optional func testOptions7() -> TestOptions
  @objc optional func testOptions8() -> TestOptions
  @objc optional func testOptions9() -> TestOptions
  @objc optional func testOptions10() -> TestOptions
  @objc optional func testOptions11() -> TestOptions
  @objc optional func testOptions12() -> TestOptions
  @objc optional func testOptions13() -> TestOptions
  @objc optional func testOptions14() -> TestOptions
  @objc optional func testOptions15() -> TestOptions
  @objc optional func testOptions16() -> TestOptions
  @objc optional func testOptions17() -> TestOptions
  @objc optional func testOptions18() -> TestOptions
  @objc optional func testOptions19() -> TestOptions
  @objc optional func testOptions20() -> TestOptions
  @objc optional func testOptions21() -> TestOptions
  @objc optional func testOptions22() -> TestOptions
  @objc optional func testOptions23() -> TestOptions
  @objc optional func testOptions24() -> TestOptions
  @objc optional func testOptions25() -> TestOptions
  @objc optional func testOptions26() -> TestOptions
  @objc optional func testOptions27() -> TestOptions
  @objc optional func testOptions28() -> TestOptions
  @objc optional func testOptions29() -> TestOptions
  @objc optional func testOptions30() -> TestOptions
  @objc optional func testOptions31() -> TestOptions
  @objc optional func testOptions32() -> TestOptions
  @objc optional func testOptions33() -> TestOptions
  @objc optional func testOptions34() -> TestOptions
  @objc optional func testOptions35() -> TestOptions
  @objc optional func testOptions36() -> TestOptions
  @objc optional func testOptions37() -> TestOptions
  @objc optional func testOptions38() -> TestOptions
  @objc optional func testOptions39() -> TestOptions
  @objc optional func testOptions40() -> TestOptions
  @objc optional func testOptions41() -> TestOptions
  @objc optional func testOptions42() -> TestOptions
  @objc optional func testOptions43() -> TestOptions
  @objc optional func testOptions44() -> TestOptions
  @objc optional func testOptions45() -> TestOptions
  @objc optional func testOptions46() -> TestOptions
  @objc optional func testOptions47() -> TestOptions
  @objc optional func testOptions48() -> TestOptions
  @objc optional func testOptions49() -> TestOptions
  @objc optional func testOptions50() -> TestOptions
  @objc optional func testOptions51() -> TestOptions
  @objc optional func testOptions52() -> TestOptions
  @objc optional func testOptions53() -> TestOptions
  @objc optional func testOptions54() -> TestOptions
  @objc optional func testOptions55() -> TestOptions
  @objc optional func testOptions56() -> TestOptions
  @objc optional func testOptions57() -> TestOptions
  @objc optional func testOptions58() -> TestOptions
  @objc optional func testOptions59() -> TestOptions
  @objc optional func testOptions60() -> TestOptions
  @objc optional func testOptions61() -> TestOptions
  @objc optional func testOptions62() -> TestOptions
  @objc optional func testOptions63() -> TestOptions
  @objc optional func testOptions64() -> TestOptions
  @objc optional func testOptions65() -> TestOptions
  @objc optional func testOptions66() -> TestOptions
  @objc optional func testOptions67() -> TestOptions
  @objc optional func testOptions68() -> TestOptions
  @objc optional func testOptions69() -> TestOptions
  @objc optional func testOptions70() -> TestOptions
  @objc optional func testOptions71() -> TestOptions
  @objc optional func testOptions72() -> TestOptions
  @objc optional func testOptions73() -> TestOptions
  @objc optional func testOptions74() -> TestOptions
  @objc optional func testOptions75() -> TestOptions
  @objc optional func testOptions76() -> TestOptions
  @objc optional func testOptions77() -> TestOptions
  @objc optional func testOptions78() -> TestOptions
  @objc optional func testOptions79() -> TestOptions
  @objc optional func testOptions80() -> TestOptions
  @objc optional func testOptions81() -> TestOptions
  @objc optional func testOptions82() -> TestOptions
}

extension RootViewController {
  func testOptions(for testNumber: Int, on testable: Testable) -> TestOptions {
    let testOptions: TestOptions? = {
      switch testNumber {
        case 0: return testable.testOptions0?()
        case 1: return testable.testOptions1?()
        case 2: return testable.testOptions2?()
        case 3: return testable.testOptions3?()
        case 4: return testable.testOptions4?()
        case 5: return testable.testOptions5?()
        case 6: return testable.testOptions6?()
        case 7: return testable.testOptions7?()
        case 8: return testable.testOptions8?()
        case 9: return testable.testOptions9?()
        case 10: return testable.testOptions10?()
        case 11: return testable.testOptions11?()
        case 12: return testable.testOptions12?()
        case 13: return testable.testOptions13?()
        case 14: return testable.testOptions14?()
        case 15: return testable.testOptions15?()
        case 16: return testable.testOptions16?()
        case 17: return testable.testOptions17?()
        case 18: return testable.testOptions18?()
        case 19: return testable.testOptions19?()
        case 20: return testable.testOptions20?()
        case 21: return testable.testOptions21?()
        case 22: return testable.testOptions22?()
        case 23: return testable.testOptions23?()
        case 24: return testable.testOptions24?()
        case 25: return testable.testOptions25?()
        case 26: return testable.testOptions26?()
        case 27: return testable.testOptions27?()
        case 28: return testable.testOptions28?()
        case 29: return testable.testOptions29?()
        case 30: return testable.testOptions30?()
        case 31: return testable.testOptions31?()
        case 32: return testable.testOptions32?()
        case 33: return testable.testOptions33?()
        case 34: return testable.testOptions34?()
        case 35: return testable.testOptions35?()
        case 36: return testable.testOptions36?()
        case 37: return testable.testOptions37?()
        case 38: return testable.testOptions38?()
        case 39: return testable.testOptions39?()
        case 40: return testable.testOptions40?()
        case 41: return testable.testOptions41?()
        case 42: return testable.testOptions42?()
        case 43: return testable.testOptions43?()
        case 44: return testable.testOptions44?()
        case 45: return testable.testOptions45?()
        case 46: return testable.testOptions46?()
        case 47: return testable.testOptions47?()
        case 48: return testable.testOptions48?()
        case 49: return testable.testOptions49?()
        case 50: return testable.testOptions50?()
        case 51: return testable.testOptions51?()
        case 52: return testable.testOptions52?()
        case 53: return testable.testOptions53?()
        case 54: return testable.testOptions54?()
        case 55: return testable.testOptions55?()
        case 56: return testable.testOptions56?()
        case 57: return testable.testOptions57?()
        case 58: return testable.testOptions58?()
        case 59: return testable.testOptions59?()
        case 60: return testable.testOptions60?()
        case 61: return testable.testOptions61?()
        case 62: return testable.testOptions62?()
        case 63: return testable.testOptions63?()
        case 64: return testable.testOptions64?()
        case 65: return testable.testOptions65?()
        case 66: return testable.testOptions66?()
        case 67: return testable.testOptions67?()
        case 68: return testable.testOptions68?()
        case 69: return testable.testOptions69?()
        case 70: return testable.testOptions70?()
        case 71: return testable.testOptions71?()
        case 72: return testable.testOptions72?()
        case 73: return testable.testOptions73?()
        case 74: return testable.testOptions74?()
        case 75: return testable.testOptions75?()
        case 76: return testable.testOptions76?()
        case 77: return testable.testOptions77?()
        case 78: return testable.testOptions78?()
        case 79: return testable.testOptions79?()
        case 80: return testable.testOptions80?()
        case 81: return testable.testOptions81?()
        case 82: return testable.testOptions82?()
        default:
          fatalError("Test options have not been defined.")
      }
    }()

    guard let testOptions = testOptions else {
      return .defaultOptions
    }

    return testOptions
  }
}

extension RootViewController {
  func performTest(_ testNumber: Int, on testable: Testable) async throws {
    switch testNumber {
      case 0: try await testable.test0()
      case 1: try await testable.test1()
      case 2: try await testable.test2()
      case 3: try await testable.test3()
      case 4: try await testable.test4()
      case 5: try await testable.test5()
      case 6: try await testable.test6()
      case 7: try await testable.test7()
      case 8: try await testable.test8()
      case 9: try await testable.test9()
      case 10: try await testable.test10()
      case 11: try await testable.test11()
      case 12: try await testable.test12()
      case 13: try await testable.test13()
      case 14: try await testable.test14()
      case 15: try await testable.test15()
      case 16: try await testable.test16()
      case 17: try await testable.test17()
      case 18: try await testable.test18()
      case 19: try await testable.test19()
      case 20: try await testable.test20()
      case 21: try await testable.test21()
      case 22: try await testable.test22()
      case 23: try await testable.test23()
      case 24: try await testable.test24()
      case 25: try await testable.test25()
      case 26: try await testable.test26()
      case 27: try await testable.test27()
      case 28: try await testable.test28()
      case 29: try await testable.test29()
      case 30: try await testable.test30()
      case 31: try await testable.test31()
      case 32: try await testable.test32()
      case 33: try await testable.test33()
      case 34: try await testable.test34()
      case 35: try await testable.test35()
      case 36: try await testable.test36()
      case 37: try await testable.test37()
      case 38: try await testable.test38()
      case 39: try await testable.test39()
      case 40: try await testable.test40()
      case 41: try await testable.test41()
      case 42: try await testable.test42()
      case 43: try await testable.test43()
      case 44: try await testable.test44()
      case 45: try await testable.test45()
      case 46: try await testable.test46()
      case 47: try await testable.test47()
      case 48: try await testable.test48()
      case 49: try await testable.test49()
      case 50: try await testable.test50()
      case 51: try await testable.test51()
      case 52: try await testable.test52()
      case 53: try await testable.test53()
      case 54: try await testable.test54()
      case 55: try await testable.test55()
      case 56: try await testable.test56()
      case 57: try await testable.test57()
      case 58: try await testable.test58()
      case 59: try await testable.test59()
      case 60: try await testable.test60()
      case 61: try await testable.test61()
      case 62: try await testable.test62()
      case 63: try await testable.test63()
      case 64: try await testable.test64()
      case 65: try await testable.test65()
      case 66: try await testable.test66()
      case 67: try await testable.test67()
      case 68: try await testable.test68()
      case 69: try await testable.test69()
      case 70: try await testable.test70()
      case 71: try await testable.test71()
      case 72: try await testable.test72()
      case 73: try await testable.test73()
      case 74: try await testable.test74()
      case 75: try await testable.test75()
      case 76: try await testable.test76()
      case 77: try await testable.test77()
      case 78: try await testable.test78()
      case 79: try await testable.test79()
      case 80: try await testable.test80()
      case 81: try await testable.test81()
      case 82: try await testable.test82()
      default:
        fatalError("Test has not been defined above.")
    }
  }
}
