name: Delete Package.resolved on Push

on: 
  push:

jobs:
  delete-and-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0

    - name: Delete File
      run: |
        FILE='UI Tests.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved'
        if test -f "$FILE"; then
          rm "$FILE"
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Delete Package.resolved via GitHub Action"
          git push
        fi
