name: Run UI Tests from superwall-me/Superwall-iOS dispatch

on:
  workflow_dispatch:
  repository_dispatch:
    types: [branch-push]

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Git User
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

    - name: Remove existing tags
      run: |
        git pull
        for tag in $(git tag); do
          if [[ $tag == run-ui-tests-* ]]; then
            git tag -d $tag
            git push origin :refs/tags/$tag
          fi
        done

    - name: Add Tag
      run: |
        TAG_NAME="run-ui-tests-${{ github.event.client_payload.commit }}"
        git tag -a $TAG_NAME -m "Add $TAG_NAME tag"
        git push origin $TAG_NAME
