name: Run UI Tests from superwall-me/Superwall-iOS dispatch

on:
  workflow_dispatch:
  repository_dispatch:
    types: [branch-push]

jobs:
  run_tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        scheme: ["UI Tests -swift -automatic", "UI Tests -swift -advanced", "UI Tests -objc -automatic", "UI Tests -objc -advanced"]

    steps:
      - name: Run curl commands
        run: |
          curl ${{ secrets.BITRISE_URL }} -L --data '{"hook_info":{"type":"bitrise","build_trigger_token":"${{ secrets.BITRISE_TOKEN }}"},"build_params":{"branch":"main","workflow_id":"primary","environments":[{"mapped_to":"IOS_SDK_COMMIT_HASH","value":"${{ github.event.client_payload.commit }}","is_expand":true},{"mapped_to":"IOS_SDK_SCHEME","value":"${{ matrix.scheme }}","is_expand":true},{"mapped_to":"IOS_SDK_AUTHOR","value":"${{ github.event.client_payload.author }}","is_expand":true},{"mapped_to":"IOS_SDK_COMMIT_MESSAGE","value":"${{ github.event.client_payload.message }}","is_expand":true}]},"triggered_by":"curl"}'
