name: Run UI Tests from superwall-me/Superwall-iOS dispatch

on:
  workflow_dispatch:
  repository_dispatch:
    types: [branch-push]

jobs:
  xcode_build:
    runs-on: macos-12
    strategy:
      matrix:
        scheme: ["UI Tests -swift -automatic"]
    env:
      PROJECT: "UI Tests.xcodeproj"
      SDK: iphonesimulator
      DESTINATION: 'platform=iOS Simulator,name=iPhone 14 Pro,OS=16.2'
      DERIVED_DATA_PATH: build_output

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Set up Xcode
      run: sudo xcode-select -s /Applications/Xcode.app/Contents/Developer

    - name: Update SPM dependency revision in project.pbxproj
      run: |
        sed -i '' "/\"SuperwallKit-iOS\" \*\/ = {/,/};/ s/revision = [a-f0-9]\{40\};/revision = ${{ github.event.client_payload.commit }};/g" "UI Tests.xcodeproj/project.pbxproj"

    - name: Run UI Tests
      run: |
        xcodebuild test -project "${{ env.PROJECT }}" \
        -scheme "${{ matrix.scheme }}" \
        -sdk "${{ env.SDK }}" \
        -destination "${{ env.DESTINATION }}" \
        -derivedDataPath "${{ env.DERIVED_DATA_PATH }}" \
        -verbose
      
    - name: Send test results to Slack
      uses: slackapi/slack-github-action@v1.14.0
      with:
        channel-id: "C052Z9LP61G"
        slack-message: ${{ steps.ui_tests.outputs.test_output }}
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
